### ISSUE TITLE
TO MANY VALUES TO UNPACK

### ISSUE THREAD

**Issue by pythonstuff8** [autodistill/autodistill#125]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar bug report.

### Bug

`Traceback (most recent call last):
  File "/home/pi/Downloads/aug.py", line 167, in <module>
    dataset = base_model.label( input_folder="output", extension=".jpg", output_folder="outputf")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Downloads/lib/python3.11/site-packages/autodistill/detection/detection_base_model.py", line 103, in label
    dataset.as_yolo(
  File "/home/pi/Downloads/lib/python3.11/site-packages/supervision/dataset/core.py", line 361, in as_yolo
    save_yolo_annotations(
  File "/home/pi/Downloads/lib/python3.11/site-packages/supervision/dataset/formats/yolo.py", line 238, in save_yolo_annotations
    lines = detections_to_yolo_annotations(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/Downloads/lib/python3.11/site-packages/supervision/dataset/formats/yolo.py", line 197, in detections_to_yolo_annotations
    for xyxy, mask, _, class_id, _ in detections:
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 5)
`

### Environment

raspberry pi 5 8gb, bookworm OS, autodistill - 0.1.24

### Minimal Reproducible Example

`from autodistill.detection import CaptionOntology

ontology=CaptionOntology({
    f"{name}": f"{name}"

})
from autodistill_grounded_sam import GroundedSAM

base_model = GroundedSAM(ontology=ontology)
dataset = base_model.label( input_folder="output", extension=".jpg", output_folder="outputf")`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pythonstuff8** [comment]
thx that worked
