### ISSUE TITLE
Error running multiple instances of ComposedDetectionModel due to cropped image file race condition.

### ISSUE THREAD

**Issue by privvyledge** [autodistill/autodistill#175]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar bug report.

### Bug

Traceback (most recent call last):
  File "/home/.../auto_labeller.py", line 1364, in <module>
    autolabeller.auto_label()
  File "/home/.../auto_label/auto_labeller.py", line 1154, in auto_label
    results, annotated_frame = self.predict(
  File "/home/.../auto_label/auto_labeller.py", line 510, in predict
    results = self.base_model.predict(frame)
  File "/home/.../auto_label/autolabeller_env/lib/python3.10/site-packages/autodistill/core/composed_detection_model.py", line 76, in predict
    result = self.classification_model.predict("temp.jpeg")
  File "/home/.../auto_label/autolabeller_env/lib/python3.10/site-packages/autodistill_clip/clip_model.py", line 67, in predict
    image = load_image(input, return_format="PIL")
  File "/home/.../auto_label/autolabeller_env/lib/python3.10/site-packages/autodistill/helpers.py", line 65, in load_image
    return Image.open(image)
  File "/home/.../auto_label/autolabeller_env/lib/python3.10/site-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'temp.jpeg'

### Environment

- autodistill: 0.1.28 - OS: Ubuntu 22.04 - Python 3.10.12

### Minimal Reproducible Example

```
from autodistill_grounding_dino import GroundingDINO  # or any detection/segmentation base model
from autodistill_clip import CLIP   # or any classification base model
from autodistill.core.composed_detection_model import ComposedDetectionModel
from autodistill.detection import CaptionOntology
from autodistill_grounded_sam import GroundedSAM
import supervision as sv

classes = ["McDonalds", "Burger King"]

SAMCLIP = CustomDetectionModel(
    detection_model=GroundedSAM(
        CaptionOntology({"logo": "logo"})
    ),
    classification_model=CLIP(
        CaptionOntology({k: k for k in classes})
    )
)
IMAGE = "logo.jpg"
results = SAMCLIP.predict(IMAGE)
image = cv2.imread(IMAGE)
annotator = sv.MaskAnnotator()
label_annotator = sv.LabelAnnotator()
labels = [
    f"{classes[class_id]} {confidence:0.2f}"
    for _, _, confidence, class_id, _ in results
]
annotated_frame = annotator.annotate(
    scene=image.copy(), detections=results
)
annotated_frame = label_annotator.annotate(
    scene=annotated_frame, labels=labels, detections=results
)
sv.plot_image(annotated_frame, size=(8, 8))
```

### Additional

The above code works. However, if running/labelling two instances simultaneously, e.g on two different terminals but from the same current working directory, one of them fails due to the error above caused by the following line 
```
# save as tempfile
region.save("temp.jpeg")
```
 in [autodistill/core/composed_detection_model.py](https://github.com/autodistill/autodistill/blob/main/autodistill/core/composed_detection_model.py#L73C13-L74C37) due to the hardcoded name "temp.jpeg" leading to a race condition between the two running instances.

A simple fix is to create a tempfile using the built-in tempfile package to handle an arbitrary number of instance.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by privvyledge** [comment]
I have created a pull request to fix this. [Link to pull request](https://github.com/autodistill/autodistill/pull/176).
