### ISSUE TITLE
SAM Clip Error

### ISSUE THREAD

**Issue by csverma610** [autodistill/autodistill#57]
Hello,

On Several images in the dataset. I get the following error. Is it the issue of error handling by the code?
  

Labeling People/beautiful-serene-black-woman-reflection-1296x728-header.jpg:   6%|▏  | 7/114 [00:39<09:57,  5.58s/it]
Traceback (most recent call last):
  File "/media/csverma/M2Disk/Projects/CompVis/ObjectDetection/AutoDistill/SAMClip_labels.py", line 10, in <module>
    base_model.label(input_folder=folder_name, output_folder="mldata")
  File "/media/csverma/M2Disk/Projects/CompVis/ObjectDetection/AutoDistill/autodistillenv/lib/python3.11/site-packages/autodistill/detection/detection_base_model.py", line 44, in label
    detections = self.predict(f_path)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/media/csverma/M2Disk/Projects/CompVis/ObjectDetection/AutoDistill/autodistillenv/lib/python3.11/site-packages/autodistill_sam_clip/sam_clip.py", line 162, in predict
    nms = sv.non_max_suppression(np.array(nms_data), 0.5)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/csverma/M2Disk/Projects/CompVis/ObjectDetection/AutoDistill/autodistillenv/lib/python3.11/site-packages/supervision/detection/utils.py", line 84, in non_max_suppression
    rows, columns = predictions.shape
    ^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
(autodistillenv) %$ open People/beautiful-serene-black-woman-reflection-1296x728-header.jpg

**Comment by capjamesg** [comment]
Thank you for creating this Issue and apologies for the delay in responding. Can I confirm the image with which you are working is a valid JPG image? If an image is corrupted, it might now load, causing `autodistill` to crash.

**Comment by csverma610** [comment]
Hello

I do not see any new codes uploaded on the site.

Can

**Comment by csverma610** [comment]
Hello

The codes are still six months old on GitHub.

Csv

**Comment by capjamesg** [comment]
The new `CustomDetectionModel` is significantly more robust and fixes several bugs with the old `autodistill-sam-clip` model`.

**Comment by csverma610** [comment]
Hello James

Thanks for the update. It is bit confusing at this time. I will dig it and
get back to you.

Csv

**Comment by capjamesg** [comment]
@csverma610 Have you solved the problem? If so, can we close this issue?

**Comment by capjamesg** [comment]
I am going to close this issue, but we can re-open it if further assistance is required.
