### ISSUE TITLE
Error in GroudingDINO label

### ISSUE THREAD

**Issue by csverma610** [autodistill/autodistill#58]
Hello,

It seems there is a minor issue in using GroundingDINO.  I get the following message: Perhaps, a simple check may solve the
issue.

Labeling People/thenewyorker_its-what-each-person-needs.jpg: 100%|█████████████████| 114/114 [00:31<00:00,  3.67it/s]
Traceback (most recent call last):
  File "/media/csverma/M2Disk/Projects/CompVis/ObjectDetection/AutoDistill/GroundingDINO_labels.py", line 10, in <module>
    base_model.label(input_folder=folder_name, output_folder='mldata')
  File "/media/csverma/M2Disk/Projects/CompVis/ObjectDetection/AutoDistill/autodistillenv/lib/python3.11/site-packages/autodistill/detection/detection_base_model.py", line 58, in label
    split_data(output_folder)
  File "/media/csverma/M2Disk/Projects/CompVis/ObjectDetection/AutoDistill/autodistillenv/lib/python3.11/site-packages/autodistill/helpers.py", line 66, in split_data
    shutil.move(os.path.join(images_dir, file + ".jpg"), train_images_dir)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/shutil.py", line 823, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path 'mldata/train/images/images2.jpg' already exists

**Comment by capjamesg** [comment]
Hello there! Autodistill does not currently delete a directory if the one you have already specified contains images. We should add a check for this; this is on my radar and something I want to action on in the future.

For now, make sure the `output_folder` you specify is a directory that does not exist. Let me know if you have any questions!
